### ISSUE TITLE
Can't seem to be able to compile it

### ISSUE THREAD

**Issue by mfirry** [Enucatl/polygen#1]
I'm trying to compile it on centos 6 (I'm an OCaml newbie) and it just won't work.
Could you add more info?

**Comment by Enucatl** [comment]
I don't know about centos, on ubuntu you have to install the ocaml-native-compilers package and then make.

**Comment by mfirry** [comment]
here's what I get:

make -C src
make[1]: Entering directory /home/papillon/polygen/src
ocamlopt.opt -c -inline 23 -unsafe parser.mli -o parser.cmi
File "parser.mli", line 1, characters 10-11:
Error: Illegal character (\)
make[1]: **\* [parser.cmi] Error 2
make[1]: Leaving directory /home/papillon/polygen/src
make: **\* [all] Error 2

**Comment by Enucatl** [comment]
weird, what's your ocaml version?

``` bash
~/code/polygen (master)$ ocamlopt.opt -v
The OCaml native-code compiler, version 4.01.0
```

**Comment by mfirry** [comment]
`ocamlopt.opt -v`
`The Objective Caml native-code compiler, version 3.11.2`
`Standard library directory: /usr/lib64/ocaml`

**Comment by Enucatl** [comment]
I installed 3.11.2 and it still compiles without errors on my machine. I think it's somehow related to the encoding, since it's complaining about the newline character...

**Comment by mfirry** [comment]
`file -bi src/parser.mli`
`text/plain; charset=us-ascii`

**Comment by Enucatl** [comment]
You could try to compile ocaml again through opam  https://opam.ocaml.org/

## 

Matteo

Вторник, 14 апреля 2015, 2:42 -07:00 от "Marco F." notifications@github.com:

**Comment by mfirry** [comment]
I'm giving up. 
Thanks a lot for your time. 
It was a toy-project (I wanted to expose productions of a given grammar as restful api via [opium](https://github.com/rgrinberg/opium)). My little knowledge of OCaml isn't enough. 
Again, thanks a lot for your time.

**Comment by Enucatl** [comment]
No problem, as an easy last chance you could download binaries from http://polygen.org/it/download

**Comment by mfirry** [comment]
Thanks. Then again, I wouldn't know how to use it from/inside opium :(
